#!/bin/sh

# MAKE-DEVICE-INODES
#
# user:
#   root    uid=0
#
# groups:
#   tty     gid=5
#   disk    gid=6
#   mem     gid=8
#   kmem    gid=9
#   dialout gid=16
#   audio   gid=17
#   video   gid=18
#
# devices:
#
#   1 char  Memory devices
#           3 = /dev/null      Null device
#           5 = /dev/zero      Null byte source
#           9 = /dev/urandom   Faster, less secure random number gen.
#
# 108 char  Device independent PPP interface
#           0 = /dev/ppp       Device independent PPP interface
#

mknod --mode=600 console c   5 1
mknod --mode=660 ppp     c 108 0
mknod --mode=666 null    c   1 3
mknod --mode=666 random  c   1 8
mknod --mode=666 urandom c   1 9
mknod --mode=666 zero    c   1 5

mknod --mode=660 fb0    c   29 0
mknod --mode=660 fb1    c   29 1

mknod --mode=660 hda    b    3 0
mknod --mode=660 hda1   b    3 1
mknod --mode=660 hda2   b    3 2
mknod --mode=660 hda3   b    3 3
mknod --mode=660 hda4   b    3 4

mknod --mode=660 sda    b    8 0
mknod --mode=660 sda1   b    8 1
mknod --mode=660 sda2   b    8 2
mknod --mode=660 sda3   b    8 3
mknod --mode=660 sda4   b    8 4

mknod --mode=660 sdb    b    8 16
mknod --mode=660 sdb1   b    8 17
mknod --mode=660 sdb2   b    8 18
mknod --mode=660 sdb3   b    8 19
mknod --mode=660 sdb4   b    8 20

mknod --mode=640 mem    c    1 1
mknod --mode=640 kmem   c    1 2
mknod --mode=644 kmsg   c    1 11
mknod --mode=600 kvm    c   10 232

mknod --mode=660 mtd0   c   90 0
mknod --mode=660 mtd1   c   90 2
mknod --mode=660 mtd2   c   90 4
mknod --mode=660 mtd3   c   90 6
mknod --mode=660 mtd4   c   90 8
mknod --mode=660 mtd5   c   90 10
mknod --mode=660 mtd6   c   90 12
mknod --mode=660 mtd7   c   90 14

mknod --mode=640 mtdblock0   b   31 0
mknod --mode=640 mtdblock1   b   31 1
mknod --mode=640 mtdblock2   b   31 2
mknod --mode=640 mtdblock3   b   31 3
mknod --mode=640 mtdblock4   b   31 4
mknod --mode=640 mtdblock5   b   31 5
mknod --mode=640 mtdblock6   b   31 6
mknod --mode=640 mtdblock7   b   31 7

mknod --mode=640 ram0   b   1 0
mknod --mode=640 ram1   b   1 1
mknod --mode=640 ram2   b   1 2
mknod --mode=640 ram3   b   1 3

mknod --mode=666 tty    c    5 0

mknod --mode=660 ttyS0  c    4 64
mknod --mode=660 ttyS1  c    4 65
mknod --mode=660 ttyS2  c    4 66
mknod --mode=660 ttyS3  c    4 67
mknod --mode=660 ttyS4  c    4 68
mknod --mode=660 ttyS5  c    4 69

mknod --mode=640 ttySA0  c  204 5
mknod --mode=640 ttySA1  c  204 6
mknod --mode=640 ttySA2  c  204 7

mknod --mode=640 cusa0  c  205 5
mknod --mode=640 cusa1  c  205 6
mknod --mode=640 cusa2  c  205 7

mknod --mode=600 initctl p

mkdir -p cgroup ; chmod 755 cgroup
mkdir -p pts    ; chmod 755 pts
mkdir -p shm    ; chmod 755 shm

ln -sf null XOR

chown 0:5   tty ttySA? cusa?
chown 0:16  ppp ttyS?
chown 0:0   cgroup pts shm null random urandom zero initctl
chown 0:18  fb0 fb1

chown 0:6   ram? hda* sda* sdb*

chown 0:9   mem kmem
chown 0:0   kmsg kvm

chown 0:0   mtd? mtdblock?
