# include once
ifndef CONSTANTS_MK

#######
####### Constants:
#######

DOWNLOAD_SERVER      = ftp://ftp.radix.pro

TOOLCHAINS_BASE_PATH = /opt/toolchain

# Target machine architrctures:

ARCH_NOARCH       = noarch
ARCH_HOST         = $(shell uname -m)-pc-linux-gnu
ARCH_I686         = i486-radix-linux-gnu
ARCH_X86_64       = x86_64-radix-linux-gnu
ARCH_A1N          = arm-a1x-eabi
ARCH_A1X          = arm-a1x-linux-gnueabi
ARCH_AT91SAM7S    = arm-at91sam7s-eabi
ARCH_TMS320DM644X = arm-dm644x-eabi
ARCH_DM644X       = arm-dm644x-linux-gnueabi
ARCH_LPC17XX      = arm-lpc17xx-uclinuxeabi
ARCH_OMAP35X      = arm-omap35x-linux-gnueabi
ARCH_OMAP543X     = arm-omap543x-linux-gnueabihf
ARCH_BCM74X       = mipsel-bcm74x-linux-gnu

#######
####### Hardware names:
#######
# noarch:
TARGET_NOARCH     = none
# Host Build:
TARGET_HOST       = host
# x86 Personal Computer:
TARGET_PC32       = pc32
# {x86|x86_64} Personal Computer:
TARGET_PC64       = pc64
# A1N newlib devices (cubieboard 1):
TARGET_CB1N       = cb1n
# A1X devices (cubieboard 1 eglibc):
TARGET_CB1X       = cb1x
# AT91SAM7S devices:
TARGET_GUARD      = guard
# DM644X newlib devices:
TARGET_VIP1830N   = vip1830n
# DM644X devices:
TARGET_VIP1830    = vip1830
# LPC17XX devices:
TARGET_L17UC      = l17uc
# OMAP35X devices:
TARGET_BEAGLE     = beagle
# OMAP543X devices:
TARGET_OMAP5UEVM  = omap5uevm
# BCM74X devices:
TARGET_B74        = b74


TARGET_ALL  = $(TARGET_NOARCH)
TARGET_ALL += $(TARGET_HOST)
TARGET_ALL += $(TARGET_PC32)
TARGET_ALL += $(TARGET_PC64)
TARGET_ALL += $(TARGET_CB1N)
TARGET_ALL += $(TARGET_CB1X)
TARGET_ALL += $(TARGET_GUARD)
TARGET_ALL += $(TARGET_VIP1830N)
TARGET_ALL += $(TARGET_VIP1830)
TARGET_ALL += $(TARGET_L17UC)
TARGET_ALL += $(TARGET_BEAGLE)
TARGET_ALL += $(TARGET_OMAP5UEVM)
TARGET_ALL += $(TARGET_B74)


###################################################################
# We can define the list of target specific FLAVOURS as
# PC64_FLAVOURS = kernel kernel-debug
# NOTE:
# The first word separated by '_' in the 'PC64_FLAVOURS'
# name should be equal to the value of TARGET_PC64
# variable in the upper case letters.
###################################################################


#######
####### Hardware IDs:
#######
      PC32_ID_STD = 04
      PC64_ID_STD = 10

      CB1N_ID_STD = 20
      CB1X_ID_STD = 21
     GUARD_ID_STD = 30
  VIP1830N_ID_STD = 40
   VIP1830_ID_STD = 41
     L17UC_ID_STD = 50
    BEAGLE_ID_STD = 60
 OMAP5UEVM_ID_STD = 70
       B74_ID_STD = 80



TARGET_ID_PC32      = $(PC32_ID_STD)
TARGET_ID_PC64      = $(PC64_ID_STD)
TARGET_ID_CB1N      = $(CB1N_ID_STD)
TARGET_ID_CB1X      = $(CB1X_ID_STD)
TARGET_ID_GUARD     = $(GUARD_ID_STD)
TARGET_ID_VIP1830N  = $(VIP1830N_ID_STD)
TARGET_ID_VIP1830   = $(VIP1830_ID_STD)
TARGET_ID_L17UC     = $(L17UC_ID_STD)
TARGET_ID_BEAGLE    = $(BEAGLE_ID_STD)
TARGET_ID_OMAP5UEVM = $(OMAP5UEVM_ID_STD)
TARGET_ID_B74       = $(B74_ID_STD)



#######
####### Available Toolchains:
#######

# NOARCH
NOARCH_TOOLCHAIN_NAME     = noarch
NOARCH_TOOLCHAIN_VERSION  = 
NOARCH_TOOLCHAIN_DIR      = 
NOARCH_TOOLCHAIN_PATH     = 
NOARCH_TARGET             = $(ARCH_NOARCH)

NOARCH_HARDWARE_VARIANTS := $(TARGET_NOARCH)


# BUILD
BUILD_TOOLCHAIN_NAME    = build
BUILD_TOOLCHAIN_VERSION = 
BUILD_TOOLCHAIN_DIR     = 
BUILD_TOOLCHAIN_PATH    = /usr
BUILD_TARGET            = $(ARCH_HOST)
BUILD_CC                = gcc
BUILD_CXX               = g++
BUILD_AS                = as
BUILD_AR                = ar
BUILD_LD                = ld
BUILD_RANLIB            = ranlib
BUILD_SIZE              = size
BUILD_STRIP             = strip
BUILD_OBJCOPY           = objcopy
BUILD_NM                = nm

BUILD_HARDWARE_VARIANTS := $(TARGET_HOST)


# I686-EGLIBC
I686_EGLIBC_TOOLCHAIN_NAME    = i686-eglibc
I686_EGLIBC_TOOLCHAIN_VERSION = 1.0.6
I686_EGLIBC_TOOLCHAIN_DIR     = i486-PC-linux-eglibc
I686_EGLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(I686_EGLIBC_TOOLCHAIN_DIR)/$(I686_EGLIBC_TOOLCHAIN_VERSION)
I686_EGLIBC_TARGET            = $(ARCH_I686)
I686_EGLIBC_CC                = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-gcc
I686_EGLIBC_CXX               = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-g++
I686_EGLIBC_AS                = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-as
I686_EGLIBC_AR                = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-ar
I686_EGLIBC_LD                = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-ld
I686_EGLIBC_RANLIB            = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-ranlib
I686_EGLIBC_SIZE              = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-size
I686_EGLIBC_STRIP             = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-strip
I686_EGLIBC_OBJCOPY           = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-objcopy
I686_EGLIBC_NM                = $(I686_EGLIBC_TOOLCHAIN_PATH)/bin/$(I686_EGLIBC_TARGET)-nm

I686_EGLIBC_HARDWARE_VARIANTS := $(TARGET_PC32)


# X86_64-EGLIBC
X86_64_EGLIBC_TOOLCHAIN_NAME    = x86_64-eglibc
X86_64_EGLIBC_TOOLCHAIN_VERSION = 1.0.6
X86_64_EGLIBC_TOOLCHAIN_DIR     = x86_64-PC-linux-eglibc
X86_64_EGLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(X86_64_EGLIBC_TOOLCHAIN_DIR)/$(X86_64_EGLIBC_TOOLCHAIN_VERSION)
X86_64_EGLIBC_TARGET            = $(ARCH_X86_64)
X86_64_EGLIBC_CC                = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-gcc
X86_64_EGLIBC_CXX               = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-g++
X86_64_EGLIBC_AS                = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-as
X86_64_EGLIBC_AR                = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-ar
X86_64_EGLIBC_LD                = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-ld
X86_64_EGLIBC_RANLIB            = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-ranlib
X86_64_EGLIBC_SIZE              = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-size
X86_64_EGLIBC_STRIP             = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-strip
X86_64_EGLIBC_OBJCOPY           = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-objcopy
X86_64_EGLIBC_NM                = $(X86_64_EGLIBC_TOOLCHAIN_PATH)/bin/$(X86_64_EGLIBC_TARGET)-nm

X86_64_EGLIBC_HARDWARE_VARIANTS := $(TARGET_PC64)


# A1X-NEWLIB
A1X_NEWLIB_TOOLCHAIN_NAME    = a1x-newlib
A1X_NEWLIB_TOOLCHAIN_VERSION = 1.0.6
A1X_NEWLIB_TOOLCHAIN_DIR     = arm-A1X-eabi-newlib
A1X_NEWLIB_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(A1X_NEWLIB_TOOLCHAIN_DIR)/$(A1X_NEWLIB_TOOLCHAIN_VERSION)
A1X_NEWLIB_TARGET            = $(ARCH_A1N)
A1X_NEWLIB_CC                = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-gcc
A1X_NEWLIB_CXX               = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-g++
A1X_NEWLIB_AS                = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-as
A1X_NEWLIB_AR                = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-ar
A1X_NEWLIB_LD                = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-ld
A1X_NEWLIB_RANLIB            = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-ranlib
A1X_NEWLIB_SIZE              = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-size
A1X_NEWLIB_STRIP             = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-strip
A1X_NEWLIB_OBJCOPY           = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-objcopy
A1X_NEWLIB_NM                = $(A1X_NEWLIB_TOOLCHAIN_PATH)/bin/$(A1X_NEWLIB_TARGET)-nm

A1X_NEWLIB_HARDWARE_VARIANTS := $(TARGET_CB1N)


# A1X-EGLIBC
A1X_EGLIBC_TOOLCHAIN_NAME    = a1x-eglibc
A1X_EGLIBC_TOOLCHAIN_VERSION = 1.0.6
A1X_EGLIBC_TOOLCHAIN_DIR     = arm-A1X-linux-eglibc
A1X_EGLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(A1X_EGLIBC_TOOLCHAIN_DIR)/$(A1X_EGLIBC_TOOLCHAIN_VERSION)
A1X_EGLIBC_TARGET            = $(ARCH_A1X)
A1X_EGLIBC_CC                = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-gcc
A1X_EGLIBC_CXX               = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-g++
A1X_EGLIBC_AS                = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-as
A1X_EGLIBC_AR                = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-ar
A1X_EGLIBC_LD                = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-ld
A1X_EGLIBC_RANLIB            = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-ranlib
A1X_EGLIBC_SIZE              = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-size
A1X_EGLIBC_STRIP             = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-strip
A1X_EGLIBC_OBJCOPY           = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-objcopy
A1X_EGLIBC_NM                = $(A1X_EGLIBC_TOOLCHAIN_PATH)/bin/$(A1X_EGLIBC_TARGET)-nm

A1X_EGLIBC_HARDWARE_VARIANTS := $(TARGET_CB1X)


# AT91SAM7S-NEWLIB
AT91SAM7S_NEWLIB_TOOLCHAIN_NAME    = at91sam7s-newlib
AT91SAM7S_NEWLIB_TOOLCHAIN_VERSION = 1.0.6
AT91SAM7S_NEWLIB_TOOLCHAIN_DIR     = arm-AT91SAM7S-eabi-newlib
AT91SAM7S_NEWLIB_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(AT91SAM7S_NEWLIB_TOOLCHAIN_DIR)/$(AT91SAM7S_NEWLIB_TOOLCHAIN_VERSION)
AT91SAM7S_NEWLIB_TARGET            = $(ARCH_AT91SAM7S)
AT91SAM7S_NEWLIB_CC                = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-gcc
AT91SAM7S_NEWLIB_CXX               = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-g++
AT91SAM7S_NEWLIB_AS                = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-as
AT91SAM7S_NEWLIB_AR                = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-ar
AT91SAM7S_NEWLIB_LD                = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-ld
AT91SAM7S_NEWLIB_RANLIB            = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-ranlib
AT91SAM7S_NEWLIB_SIZE              = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-size
AT91SAM7S_NEWLIB_STRIP             = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-strip
AT91SAM7S_NEWLIB_OBJCOPY           = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-objcopy
AT91SAM7S_NEWLIB_NM                = $(AT91SAM7S_NEWLIB_TOOLCHAIN_PATH)/bin/$(AT91SAM7S_NEWLIB_TARGET)-nm

AT91SAM7S_NEWLIB_HARDWARE_VARIANTS := $(TARGET_GUARD)


# DM644X-NEWLIB
DM644X_NEWLIB_TOOLCHAIN_NAME    = dm644x-newlib
DM644X_NEWLIB_TOOLCHAIN_VERSION = 1.0.6
DM644X_NEWLIB_TOOLCHAIN_DIR     = arm-DM644X-eabi-newlib
DM644X_NEWLIB_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(DM644X_NEWLIB_TOOLCHAIN_DIR)/$(DM644X_NEWLIB_TOOLCHAIN_VERSION)
DM644X_NEWLIB_TARGET            = $(ARCH_TMS320DM644X)
DM644X_NEWLIB_CC                = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-gcc
DM644X_NEWLIB_CXX               = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-g++
DM644X_NEWLIB_AS                = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-as
DM644X_NEWLIB_AR                = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-ar
DM644X_NEWLIB_LD                = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-ld
DM644X_NEWLIB_RANLIB            = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-ranlib
DM644X_NEWLIB_SIZE              = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-size
DM644X_NEWLIB_STRIP             = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-strip
DM644X_NEWLIB_OBJCOPY           = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-objcopy
DM644X_NEWLIB_NM                = $(DM644X_NEWLIB_TOOLCHAIN_PATH)/bin/$(DM644X_NEWLIB_TARGET)-nm

DM644X_NEWLIB_HARDWARE_VARIANTS := $(TARGET_VIP1830N)


# DM644X-EGLIBC
DM644X_EGLIBC_TOOLCHAIN_NAME    = dm644x-eglibc
DM644X_EGLIBC_TOOLCHAIN_VERSION = 1.0.6
DM644X_EGLIBC_TOOLCHAIN_DIR     = arm-DM644X-linux-eglibc
DM644X_EGLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(DM644X_EGLIBC_TOOLCHAIN_DIR)/$(DM644X_EGLIBC_TOOLCHAIN_VERSION)
DM644X_EGLIBC_TARGET            = $(ARCH_DM644X)
DM644X_EGLIBC_CC                = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-gcc
DM644X_EGLIBC_CXX               = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-g++
DM644X_EGLIBC_AS                = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-as
DM644X_EGLIBC_AR                = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-ar
DM644X_EGLIBC_LD                = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-ld
DM644X_EGLIBC_RANLIB            = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-ranlib
DM644X_EGLIBC_SIZE              = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-size
DM644X_EGLIBC_STRIP             = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-strip
DM644X_EGLIBC_OBJCOPY           = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-objcopy
DM644X_EGLIBC_NM                = $(DM644X_EGLIBC_TOOLCHAIN_PATH)/bin/$(DM644X_EGLIBC_TARGET)-nm

DM644X_EGLIBC_HARDWARE_VARIANTS := $(TARGET_VIP1830)


# LPC17XX-UCLIBC
LPC17XX_UCLIBC_TOOLCHAIN_NAME    = lpc17xx-uclibc
LPC17XX_UCLIBC_TOOLCHAIN_VERSION = 1.0.6
LPC17XX_UCLIBC_TOOLCHAIN_DIR     = arm-LPC17XX-uclinuxeabi
LPC17XX_UCLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(LPC17XX_UCLIBC_TOOLCHAIN_DIR)/$(LPC17XX_UCLIBC_TOOLCHAIN_VERSION)
LPC17XX_UCLIBC_TARGET            = $(ARCH_LPC17XX)
LPC17XX_UCLIBC_CC                = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-gcc
LPC17XX_UCLIBC_CXX               = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-g++
LPC17XX_UCLIBC_AS                = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-as
LPC17XX_UCLIBC_AR                = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-ar
LPC17XX_UCLIBC_LD                = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-ld
LPC17XX_UCLIBC_RANLIB            = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-ranlib
LPC17XX_UCLIBC_SIZE              = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-size
LPC17XX_UCLIBC_STRIP             = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-strip
LPC17XX_UCLIBC_OBJCOPY           = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-objcopy
LPC17XX_UCLIBC_NM                = $(LPC17XX_UCLIBC_TOOLCHAIN_PATH)/bin/$(LPC17XX_UCLIBC_TARGET)-nm

LPC17XX_UCLIBC_HARDWARE_VARIANTS := $(TARGET_L17UC)


# OMAP35X-EGLIBC
OMAP35X_EGLIBC_TOOLCHAIN_NAME    = omap35x-eglibc
OMAP35X_EGLIBC_TOOLCHAIN_VERSION = 1.0.6
OMAP35X_EGLIBC_TOOLCHAIN_DIR     = arm-OMAP35X-linux-eglibc
OMAP35X_EGLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(OMAP35X_EGLIBC_TOOLCHAIN_DIR)/$(OMAP35X_EGLIBC_TOOLCHAIN_VERSION)
OMAP35X_EGLIBC_TARGET            = $(ARCH_OMAP35X)
OMAP35X_EGLIBC_CC                = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-gcc
OMAP35X_EGLIBC_CXX               = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-g++
OMAP35X_EGLIBC_AS                = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-as
OMAP35X_EGLIBC_AR                = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-ar
OMAP35X_EGLIBC_LD                = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-ld
OMAP35X_EGLIBC_RANLIB            = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-ranlib
OMAP35X_EGLIBC_SIZE              = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-size
OMAP35X_EGLIBC_STRIP             = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-strip
OMAP35X_EGLIBC_OBJCOPY           = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-objcopy
OMAP35X_EGLIBC_NM                = $(OMAP35X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP35X_EGLIBC_TARGET)-nm

OMAP35X_EGLIBC_HARDWARE_VARIANTS := $(TARGET_BEAGLE)


# OMAP543X-EGLIBC
OMAP543X_EGLIBC_TOOLCHAIN_NAME    = omap543x-eglibc
OMAP543X_EGLIBC_TOOLCHAIN_VERSION = 1.0.6
OMAP543X_EGLIBC_TOOLCHAIN_DIR     = arm-OMAP543X-linux-eglibc
OMAP543X_EGLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(OMAP543X_EGLIBC_TOOLCHAIN_DIR)/$(OMAP543X_EGLIBC_TOOLCHAIN_VERSION)
OMAP543X_EGLIBC_TARGET            = $(ARCH_OMAP543X)
OMAP543X_EGLIBC_CC                = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-gcc
OMAP543X_EGLIBC_CXX               = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-g++
OMAP543X_EGLIBC_AS                = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-as
OMAP543X_EGLIBC_AR                = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-ar
OMAP543X_EGLIBC_LD                = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-ld
OMAP543X_EGLIBC_RANLIB            = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-ranlib
OMAP543X_EGLIBC_SIZE              = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-size
OMAP543X_EGLIBC_STRIP             = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-strip
OMAP543X_EGLIBC_OBJCOPY           = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-objcopy
OMAP543X_EGLIBC_NM                = $(OMAP543X_EGLIBC_TOOLCHAIN_PATH)/bin/$(OMAP543X_EGLIBC_TARGET)-nm

OMAP543X_EGLIBC_HARDWARE_VARIANTS := $(TARGET_OMAP5UEVM)


# BCM74X-EGLIBC
BCM74X_EGLIBC_TOOLCHAIN_NAME    = bcm74x-eglibc
BCM74X_EGLIBC_TOOLCHAIN_VERSION = 1.0.6
BCM74X_EGLIBC_TOOLCHAIN_DIR     = mipsel-BCM74X-linux-eglibc
BCM74X_EGLIBC_TOOLCHAIN_PATH    = $(TOOLCHAINS_BASE_PATH)/$(BCM74X_EGLIBC_TOOLCHAIN_DIR)/$(BCM74X_EGLIBC_TOOLCHAIN_VERSION)
BCM74X_EGLIBC_TARGET            = $(ARCH_BCM74X)
BCM74X_EGLIBC_CC                = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-gcc
BCM74X_EGLIBC_CXX               = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-g++
BCM74X_EGLIBC_AS                = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-as
BCM74X_EGLIBC_AR                = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-ar
BCM74X_EGLIBC_LD                = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-ld
BCM74X_EGLIBC_RANLIB            = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-ranlib
BCM74X_EGLIBC_SIZE              = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-size
BCM74X_EGLIBC_STRIP             = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-strip
BCM74X_EGLIBC_OBJCOPY           = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-objcopy
BCM74X_EGLIBC_NM                = $(BCM74X_EGLIBC_TOOLCHAIN_PATH)/bin/$(BCM74X_EGLIBC_TARGET)-nm

BCM74X_EGLIBC_HARDWARE_VARIANTS := $(TARGET_B74)



TOOLCHAIN_NAMES = $(NOARCH_TOOLCHAIN_NAME) \
                  $(BUILD_TOOLCHAIN_NAME) \
                  $(I686_EGLIBC_TOOLCHAIN_NAME) \
                  $(X86_64_EGLIBC_TOOLCHAIN_NAME) \
                  $(A1X_NEWLIB_TOOLCHAIN_NAME) \
                  $(A1X_EGLIBC_TOOLCHAIN_NAME) \
                  $(AT91SAM7S_NEWLIB_TOOLCHAIN_NAME) \
                  $(DM644X_NEWLIB_TOOLCHAIN_NAME) \
                  $(DM644X_EGLIBC_TOOLCHAIN_NAME) \
                  $(LPC17XX_UCLIBC_TOOLCHAIN_NAME) \
                  $(OMAP35X_EGLIBC_TOOLCHAIN_NAME) \
                  $(OMAP543X_EGLIBC_TOOLCHAIN_NAME) \
                  $(BCM74X_EGLIBC_TOOLCHAIN_NAME)


COMPONENT_TOOLCHAINS = $(NOARCH_TOOLCHAIN_NAME) \
                       $(BUILD_TOOLCHAIN_NAME) \
                       $(I686_EGLIBC_TOOLCHAIN_NAME) \
                       $(X86_64_EGLIBC_TOOLCHAIN_NAME) \
                       $(A1X_NEWLIB_TOOLCHAIN_NAME) \
                       $(A1X_EGLIBC_TOOLCHAIN_NAME) \
                       $(AT91SAM7S_NEWLIB_TOOLCHAIN_NAME) \
                       $(DM644X_NEWLIB_TOOLCHAIN_NAME) \
                       $(DM644X_EGLIBC_TOOLCHAIN_NAME) \
                       $(LPC17XX_UCLIBC_TOOLCHAIN_NAME) \
                       $(OMAP35X_EGLIBC_TOOLCHAIN_NAME) \
                       $(OMAP543X_EGLIBC_TOOLCHAIN_NAME) \
                       $(BCM74X_EGLIBC_TOOLCHAIN_NAME)



    NOARCH_TOOLCHAIN = $(NOARCH_TOOLCHAIN_NAME)
     BUILD_TOOLCHAIN = $(BUILD_TOOLCHAIN_NAME)
      PC32_TOOLCHAIN = $(I686_EGLIBC_TOOLCHAIN_NAME)
      PC64_TOOLCHAIN = $(X86_64_EGLIBC_TOOLCHAIN_NAME)
      CB1N_TOOLCHAIN = $(A1X_NEWLIB_TOOLCHAIN_NAME)
      CB1X_TOOLCHAIN = $(A1X_EGLIBC_TOOLCHAIN_NAME)
     GUARD_TOOLCHAIN = $(AT91SAM7S_TOOLCHAIN_NAME)
  VIP1830N_TOOLCHAIN = $(DM644X_NEWLIB_TOOLCHAIN_NAME)
   VIP1830_TOOLCHAIN = $(DM644X_EGLIBC_TOOLCHAIN_NAME)
     L17UC_TOOLCHAIN = $(LPC17XXX_UCLIBC_TOOLCHAIN_NAME)
    BEAGLE_TOOLCHAIN = $(OMAP35X_EGLIBC_TOOLCHAIN_NAME)
 OMAP5UEVM_TOOLCHAIN = $(OMAP543X_EGLIBC_TOOLCHAIN_NAME)
       B74_TOOLCHAIN = $(BCM74X_EGLIBC_TOOLCHAIN_NAME)


#
# HOST variable should be set up for each makefile !!! NOT FACT !!!
#

HOST = $(ARCH_HOST)


CONSTANTS_MK=1
endif
